version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes: 
      - /app/node_modules
      - ./src:/app/src
  # Service to run test
  node-app-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./src:/app/src
    command: ["npm", "run", "test"]