# In case of using Docker we need to have super user permissions
sudo: required
services:
  - docker

before_install:
  - cd ./app-travis-ci-aws 
  - docker build -t denysderkach/app-travis-ci-aws -f Dockerfile.dev .

script:
  - docker run -e CI=true denysderkach/app-travis-ci-aws:latest npm run test

deploy:
  provider: elasticbeantalk
  region: "us-east-1"
  app: "app-travis-ci-aws"
  env: "AppTravisCiAws-env"
  bucket_name: "elasticbeanstalk-us-east-1-293982140933"
  bucket_path: "app-travis-ci-aws"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY_ID"
  secret_access_key:
    secure: "$AWS_SECRET_KEY_ID"