version: '3'
services:
  redis-server:
    image: 'redis'
  node-app:
    # Container restart - default is no
    # Possible variants - no, always, on-failture, unless-stopped
    restart: always
    build: .
    ports:
      - '3000:3000'