FROM node:alpine

# Specifying work directory
WORKDIR /app

# Copying files from project to docker image
COPY ./package.json .

# Installing dependencies
RUN npm i

COPY ./src ./src
COPY ./public ./public


CMD ["npm", "run", "start"]